---
title: "Outlier Detection"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny 
---

```{r setup, include=FALSE}
library(flexdashboard)
library(markdown)
library(shiny)
library(ggplot2)
library(plotly)
library(knitr)
library(fitdistrplus)
```

```{r}
data_in <- reactive({

    inFile <- input$file_data

    if (is.null(inFile)) {

    } else {

      data<- read.csv(inFile$datapath,na.strings=c(""," ","NA"))

      #Identify numeric, integer, logical, factor and character variables
      var<- names(data)
      type<- sapply(data, class)
      var_numeric<- var[which(type %in% c("numeric","integer"))]
      var_logical<- var[which(type %in% c("logical"))]
      var_factor<- var[which(type %in% c("factor"))]
      var_character<- var[which(type %in% c("character"))]
    }

    list(data=data, var_numeric=var_numeric, var_logical=var_logical, var_factor=var_factor, var_character=var_character)
  })
```

Sidebar {.sidebar}
===================================== 

```{r}
# shiny inputs defined here
fileInput('file_data', 'Import data:',accept=c("rds"))

selectInput('var', 'Select variable:',"")

sliderInput("nbBins", label = "Number of bins:",
            min = 1, max = 100, value = 30, step = 1)
```

```{r}
observeEvent(input$file_data, {

    var_numeric<- data_in()$var_numeric

    updateSelectInput(session, inputId = "var", choices = c( var_numeric))

  })
```


Tukey's test {data-orientation=rows}
=====================================  


```{r}
#function: outlier detection based on Tukey's test

tukey_test <- function(data,var){
    #Calculate Q1 (25th percentile of the data) for the given vairiable
    Q1 = quantile(data[,var],0.25)
    
    #Calculate Q3 (75th percentile of the data) for the given variable
    Q3 = quantile(data[,var],0.75)
    
    #Use the interquartile range to calculate an outlier step (1.5 times the interquartile       range)
    step = 1.5*(Q3-Q1)
    
    outliers <- ((data[,var] <= Q1 - step) | (data[,var] >= Q3 + step))
    
    return(outliers)
}
```




```{r results="hide"}
outliers <- reactive({
  tukey_test(data_in()$data,input$var)
  })
```


Row
-----------------------------------------------------------------------

### Number of Outliers
```{r}
renderValueBox({
  outliers_nb <- sum(outliers())
  valueBox(outliers_nb,color="green")
})
```

### Proportion of Outliers
```{r}
renderValueBox({
  outliers_rate <- round(sum(outliers())/nrow(data_in()$data)*100,digits = 1)
  outliers_rate_format <- paste(outliers_rate,"%")
  valueBox(outliers_rate_format,color="green")
})
```


Column {data-width=650}
-----------------------------------------------------------------------

### Histogram {data-height=600}


```{r}
renderPlotly({
  
  #Estimate the parameters of the distribution
  col_data <- NULL
  col_data <- unlist(data_in()$data[, input$var])
  fit <- fitdist(data=col_data, distr='norm')
  params <- fit$estimate
  
   p<- ggplot(data=data_in()$data,aes_string(input$var)) +
       geom_histogram(aes(y = ..density..),bins=as.numeric(input$nbBins),
                  colour = "blue") +
       ggtitle(paste("Distribution of",input$var)) +
       #Overlay normal curve to histogram
       stat_function(fun = dnorm, #x=col_data,  
                        args=list(mean=params[1], sd=params[2]),
                        lwd=2, col='red',alpha = 0.4)
    
 
   ggplotly(p)
    })
```

Column {data-width=350}
-----------------------------------------------------------------------

### Table with outliers

```{r}
renderTable({
    data_in()$data[outliers(),]
})
```

Standard Deviation test {data-orientation=rows}
=====================================     


```{r}

sd_test <- function(data,var)
{
  sdfactor <- 2
  avg <- mean(unlist(data_in()$data[,var]),na.rm=T)
  sd <- sd(unlist(data_in()$data[,var]),na.rm=T)
  upperThresh <- avg+sdfactor*sd
  lowerThresh <- avg-sdfactor*sd
  outliers <- data[(data_in()$data[,var]>upperThresh | data_in()$data[,var] < lowerThresh),]
  return(list(outliers=outliers,avg=avg,sd=sd,upperThresh=upperThresh,lowerThresh=lowerThresh))
}
```

```{r}
stdoutliers <- reactive({sd_test(data_in()$data,input$var)})
```


Row 
-------------------------------------

### Number of Outliers

```{r}
renderValueBox({
  no_of_outliers <- nrow(stdoutliers()$outliers)
  valueBox(no_of_outliers,color = "green")
})
```

### Proportion of Outliers

```{r}
renderValueBox({
  no_of_outliers <- nrow(stdoutliers()$outliers)
  outlier_prop <-round( no_of_outliers/nrow(data_in()$data)*100,1)
  valueBox(paste(outlier_prop,"%"),color = "green")
})
```
   

Column {data-width=650}
-------------------------------------

### Distribution Histogram

```{r}
col_data <- NULL

renderPlot({
  col_data <- unlist(data_in()$data[,input$var])
  fit <- fitdist(data=col_data, distr='norm')
  param <- fit$estimate
  ggplot(data_in()$data,aes_string(input$var))+geom_histogram(aes(y=..density..),color="blue",
                                      bins=as.numeric(input$nbBins),alpha=0.4)+
                              geom_vline(xintercept=stdoutliers()$avg,
                                         color="darkgreen")+
                              geom_vline(xintercept=stdoutliers()$upperThresh,
                                         color="darkgreen")+
                              geom_vline(xintercept=stdoutliers()$lowerThresh,
                                         color="darkgreen")+
                              geom_text(x=stdoutliers()$avg-500,y=5000,                                    angle=90,label=paste("avg.=",round(stdoutliers()$avg),2))+
                              geom_text(x=stdoutliers()$upperThresh-500,y=5000,                                   angle=90,label=paste("Upper=",round(stdoutliers()$upperThresh),2))+
                              geom_text(x=stdoutliers()$lowerThresh-500,y=5000,                                   angle=90,label=paste("Lower=",round(stdoutliers()$lowerThresh),2)) +
   stat_function(fun = dnorm,  
                        args=list(mean=param[1], sd=param[2]),
                        lwd=2, col='red',alpha = 0.4)
 
 

})
 
    
                         
```

### Box Plot with Outliers
```{r}
renderPlot({
  ggplot(data_in()$data,aes_string(y=input$var,x="1"))+geom_boxplot(outlier.colour = "red")+coord_flip()
 
})


```





Column {data-width=650}
-------------------------------------
   
### Outlier Details
```{r}

renderTable({
  stdoutliers()$outliers
})

```

```{r}
```   
    
